# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "gnome-software-3.26.2";

  src = fetchurl {
    url = mirror://gnome/sources/gnome-software/3.26/gnome-software-3.26.2.tar.xz;
    sha256 = "0407aee0828fd1a542cbefcae8f7f508babffff3c6562303c8b4da1fda377581";
  };
}
