# Autogenerated by maintainers/scripts/gnome.sh update

fetchurl: {
  name = "epiphany-3.26.2";

  src = fetchurl {
    url = mirror://gnome/sources/epiphany/3.26/epiphany-3.26.2.tar.xz;
    sha256 = "46757b74d1e7d7f78a7c6377dba2db4e2ed470efe4cc7067d4f0facf1d3ec3a9";
  };
}
